### ISSUE TITLE
Cannot authorize google account

### ISSUE THREAD

**Issue by DiyRex** [rokibhasansagar/BhadooGDIndex#1]
Authorization Error
Error 403: access_denied
The developer hasn’t given you access to this app. It’s currently being tested and it hasn’t been verified by Google. If you think you should have access, contact the developer (rclone4phantom@googlegroups.com).

**Comment by rokibhasansagar** [comment]
> Authorization Error

I see. I haven't published this API Project from Google Cloud Console for Public use. It needs yet to be Verified.

You need to use your own _CLIENT ID_ and _CLIENT SECRET_ from https://console.developers.google.com/apis/credentials and replace all instance of my codes with yours, in Generator worker as-well-as other files inside "worker" folder.

Moreover, this repository is merged with Updates from Upstream until February, and the Main Author Added "[Secure OAuth Flow](https://gitlab.com/GoogleDriveIndex/Google-Drive-Index/-/commit/9059a4e343ca99ed9c25a5c7a0dbad36b2a1dcaa)" which changes many codes for new Security Reasons. I haven't got time to test the updated code, that's why I haven't merged them here yet.

After testing, I will Merge the updates and Publish the Project for Public use.
Till then, it's better to use your own Project Credentials.

**Comment by rokibhasansagar** [comment]
### Fixed with latest commit. But there's a guide which needs to be followed.

**_If you are an advanced user:_** https://github.com/rokibhasansagar/BhadooGDIndex#how-to-make-your-own-cloudflare-worker-and-index-from-scratch

**_If you are just a beginner:_** https://github.com/rokibhasansagar/BhadooGDIndex#how-to-use-this-project-as-is-and-make-your-index-the-easy-way
