### ISSUE TITLE
fix the code generator

### ISSUE THREAD

**Issue by arunpc4u** [rokibhasansagar/BhadooGDIndex#2]
error on https://bhadoogen.phantomzone.workers.dev/

Access blocked: PhantomDrive for fr3aky’s request is invalid

**Comment by rokibhasansagar** [comment]
### Fixed with latest commit. But there's a guide which needs to be followed.

**_If you are an advanced user:_** https://github.com/rokibhasansagar/BhadooGDIndex#how-to-make-your-own-cloudflare-worker-and-index-from-scratch

**_If you are just a beginner:_** https://github.com/rokibhasansagar/BhadooGDIndex#how-to-use-this-project-as-is-and-make-your-index-the-easy-way
